# Generated by Django 5.1.2 on 2024-10-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
